/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContextProcessRouteImport } from './routes/process-context.tsx'
import { Route as IndexRouteImport } from './routes/index'

const ContextProcessRoute = ContextProcessRouteImport.update({
  id: '/context-process',
  path: '/context-process',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/context-process': typeof ContextProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context-process': typeof ContextProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/context-process': typeof ContextProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/context-process'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/context-process'
  id: '__root__' | '/' | '/context-process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextProcessRoute: typeof ContextProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/context-process': {
      id: '/context-process'
      path: '/context-process'
      fullPath: '/context-process'
      preLoaderRoute: typeof ContextProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextProcessRoute: ContextProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
