/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PfdGraphRouteImport } from './routes/pfd-graph'
import { Route as IndexRouteImport } from './routes/index'

const PfdGraphRoute = PfdGraphRouteImport.update({
  id: '/pfd-graph',
  path: '/pfd-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pfd-graph': typeof PfdGraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pfd-graph': typeof PfdGraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pfd-graph': typeof PfdGraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pfd-graph'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pfd-graph'
  id: '__root__' | '/' | '/pfd-graph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PfdGraphRoute: typeof PfdGraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pfd-graph': {
      id: '/pfd-graph'
      path: '/pfd-graph'
      fullPath: '/pfd-graph'
      preLoaderRoute: typeof PfdGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PfdGraphRoute: PfdGraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
